CREATE TABLE STUDENT_DATA
(
	NO		INT,
	NAME	VARCHAR(20),
	CITY	VARCHAR(20),
	DID		INT,
)
INSERT INTO STUDENT_DATA VALUES(101,'RAJU','RAJKOT',10)
INSERT INTO STUDENT_DATA VALUES(102,'AMIT','AHMEDABAD',20)
INSERT INTO STUDENT_DATA VALUES(103,'SANJAY','BARODA',40)
INSERT INTO STUDENT_DATA VALUES(104,'NEHA','RAJKOT',20)
INSERT INTO STUDENT_DATA VALUES(105,'MEERA','AHMEDABAD',30)
INSERT INTO STUDENT_DATA VALUES(106,'MAHESH','BARODA',10)

SELECT * FROM STUDENT_DATA

CREATE TABLE ACADEMIC
(
	RNO		INT,
	SPI 	DECIMAL(8,2),
	BKLOG	INT
)

INSERT INTO ACADEMIC VALUES(101,8.8,0)
INSERT INTO ACADEMIC VALUES(102,9.2,2)
INSERT INTO ACADEMIC VALUES(103,7.6,1)
INSERT INTO ACADEMIC VALUES(104,8.2,4)
INSERT INTO ACADEMIC VALUES(105,7.0,2)
INSERT INTO ACADEMIC VALUES(106,8.9,3)

SELECT * FROM ACADEMIC

CREATE TABLE DEPARTMENT
(
	DID	INT,
	DNAME	VARCHAR(20)	
)

INSERT INTO DEPARTMENT VALUES(10,'COMPUTER')
INSERT INTO DEPARTMENT VALUES(20,'ELECTRICAL')
INSERT INTO DEPARTMENT VALUES(30,'MECHANICAL')
INSERT INTO DEPARTMENT VALUES(40,'CIVIL')

SELECT * FROM DEPARTMENT

--Part – A

--1
--Display details of students who are from computer department.
SELECT * FROM STUDENT_DATA WHERE DID IN (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER')

--2
--Displays name of students whose SPI is more than 8.
SELECT NAME FROM STUDENT_DATA WHERE NO IN(SELECT RNO FROM ACADEMIC WHERE SPI > 8)

--3
--Display details of students of computer department who belongs to Rajkot city.
SELECT * FROM STUDENT_DATA WHERE CITY='RAJKOT' AND DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER')

--4
--Find total number of students of electrical department.
SELECT COUNT(NO) FROM STUDENT_DATA WHERE DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL')

--5
--Display name of student who is having maximum SPI.
SELECT NAME FROM STUDENT_DATA WHERE NO IN(SELECT RNO FROM ACADEMIC WHERE SPI IN (SELECT MAX(SPI) FROM ACADEMIC))

--6
--Display details of students having more than 1 backlog.
SELECT * FROM STUDENT_DATA WHERE NO IN(SELECT RNO FROM ACADEMIC WHERE BKLOG > 1)


--Part – B

--1
--Display name of students who are either from computer department or from mechanical department.
SELECT NAME FROM STUDENT_DATA WHERE DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER' OR DNAME='MECHANICAL')

--2.
--Display name of students who are in same department as 102 studying in.
SELECT NAME FROM STUDENT_DATA WHERE DID IN(SELECT DID FROM DEPARTMENT WHERE DID IN(SELECT DID FROM STUDENT_DATA WHERE NO=102))

--Part – C

--1
--Display name of students whose SPI is more than 9 and who is from electrical department.
SELECT NAME FROM STUDENT_DATA WHERE DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL') AND NO IN(SELECT RNO FROM ACADEMIC WHERE SPI>9)

--2
--Display name of student who is having second highest SPI.
SELECT NAME FROM STUDENT_DATA WHERE NO IN(SELECT RNO FROM ACADEMIC WHERE SPI IN(SELECT MAX(SPI) FROM ACADEMIC WHERE SPI<(SELECT MAX(SPI) FROM ACADEMIC)))

--3
--Display city names whose students branch wise SPI is 9.2
SELECT CITY FROM STUDENT_DATA WHERE NO IN(SELECT RNO FROM ACADEMIC WHERE SPI=9.2 )GROUP BY DID,CITY