SELECT *FROM PERSON
--Part – A
--1
--Find all persons with their department name & code.
SELECT PERSON.*,DEPT.DEPARTMENTCODE,DEPT.DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID

--2
--Find the person's name whose department is in C-Block.
SELECT PERSONNAME,LOCATION FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE LOCATION='C-BLOCK'

--3
--Retrieve person name, salary & department name who belongs to Jamnagar city.
SELECT PERSONNAME,SALARY,DEPT.DEPARTMENTNAME,PERSON.CITY FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE PERSON.CITY='JAMNAGAR'

--4
--Retrieve person name, salary & department name who does not belong to Rajkot city.
SELECT PERSONNAME,SALARY,DEPT.DEPARTMENTNAME,PERSON.CITY FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE PERSON.CITY<>'RAJKOT'

--5
--Retrieve person’s name of the person who joined the Civil department after 1-Aug-2001.
SELECT PERSONNAME,JOININGDATE,DEPT.DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE DEPT.DEPARTMENTNAME='CIVIL' AND JOININGDATE >'2001-08-01'

--6
--Find details of all persons who belong to the computer department.
SELECT PERSON.*,DEPT.DEPARTMENTNAME FROM PERSON JOIN DEPT ON  PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE DEPT.DEPARTMENTNAME='COMPUTER'

--7
--Display all the person's name with the department whose joining date difference with the current date is more than 365 days.
SELECT PERSONNAME,DEPT.DEPARTMENTNAME ,DATEDIFF(DAY,PERSON.JOININGDATE,GETDATE()) FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE DATEDIFF(DAY,PERSON.JOININGDATE,GETDATE())>365

--8
--Find department wise person counts.
SELECT COUNT(PERSONID),DEPT.DEPARTMENTNAME FROM PERSON JOIN DEPT ON  PERSON.DEPARTMENTID=DEPT.DEPARTMENTID GROUP BY DEPT.DEPARTMENTNAME

--9
--Give department wise maximum & minimum salary with department name.
SELECT MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM,DEPT.DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID GROUP BY DEPT.DEPARTMENTNAME

--10
--Find city wise total, average, maximum and minimum salary.
SELECT MAX(SALARY)AS MAXIMUM,MIN(SALARY) AS MINIMUM,AVG(SALARY) AS AVERAGE,SUM(SALARY) AS TOTAL,CITY FROM PERSON GROUP BY CITY

--11
--Find the average salary of a person who belongs to Ahmedabad city.
SELECT AVG(SALARY) AS AVERAGE,CITY FROM PERSON WHERE CITY='AHMEDABAD' GROUP BY CITY

--12
--Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In--single column)SELECT PERSONNAME+' LIVES IN '+CITY+' AND WORKS IN '+DEPT.DEPARTMENTNAME FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID--Part – B
--1
--Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In--single column)
SELECT PERSONNAME+' EARNS '+CAST(SALARY AS VARCHAR)+' FROM '+DEPT.DEPARTMENTNAME+' DEPARTMENT ' FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID

--2
--Find city & department wise total, average & maximum salaries.
SELECT CITY,DEPARTMENTNAME, SUM(SALARY) AS TOTAL ,AVG(SALARY) AS AVERAGE, MAX(SALARY) AS MAXIUM FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID GROUP BY CITY,DEPARTMENTNAME

--3
--Find all persons who do not belong to any department.
SELECT PERSON.* FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE DEPT.DEPARTMENTID IS NULL

--4
--Find all departments whose total salary is exceeding 100000.
SELECT DEPT.DEPARTMENTID,SUM(PERSON.SALARY) FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID GROUP BY DEPT.DEPARTMENTID HAVING SUM(PERSON.SALARY) > 100000

--Part – C
--1
--List all departments who have no person.
SELECT DEPARTMENTNAME FROM DEPT RIGHT JOIN PERSON ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE PERSON.PERSONID IS NULL

--2--List out department names in which more than two persons are working.
SELECT DEPARTMENTNAME FROM DEPT JOIN PERSON ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID GROUP BY DEPARTMENTNAME HAVING COUNT(PERSON.PERSONID) >2 

--3--Give a 10% increment in the computer department employee’s salary. (Use Update)UPDATE PERSON SET SALARY=SALARY*1.10 FROM PERSON JOIN DEPT ON PERSON.DEPARTMENTID=DEPT.DEPARTMENTID WHERE DEPARTMENTNAME='COMPUTER'